# base image with specified node version (node:<version>)
FROM node:10

ENV NPM_CONFIG_LOGLEVEL info
    NODE_ENV production


# application's default port
# only these ports the Docker container is listening to, only they are exposed
EXPOSE 8080