version: '3.6'

services:
  graphql-db:
    image: postgres:11.1
    container_name: graphql-realtime-db
    restart: always
    environment:
      # if not defined the default user is 'postgres'  
      # POSTGRES_USER: rstardev 
      POSTGRES_PASSWORD: mysecretpassword
      
      # the default database that is created, default is the value of POSTGRES_USER
      # POSTGRES_DB: mydb
      
      # where to store the DB files - the default is '/var/lib/postgresql/data'
      # PGDATA: 

    volumes:
      # use the named volume
      - graphql-db-data:/var/lib/postgresql/data    

  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-alpha32
    container_name: graphql-realtime-engine
    depends_on:
      - graphql-db
    restart: always
    ports:
      - 8080:8080
    environment:
      # HASURA_GRAPHQL_DATABASE_URL: postgres://username:password@hostname:port/dbname
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:mysecretpassword@graphql-realtime-db:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## uncomment next line to set an access key
      # HASURA_GRAPHQL_ACCESS_KEY: mysecretaccesskey

# Define common named volumes
volumes:
  graphql-db-data:      