service: my-youtube-download

custom:
  # define the name of the DynamoDB Table here as it's ARN will be used in the IAM roles also
  s3Bucket: ${self:service}-${self:provider.stage}

provider:
  name: aws
  runtime: nodejs8.10
  # timeout: 10 # global timeout - optional, in seconds, default is 6

  stage: dev
  region: eu-central-1

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "TranscodedBucket" } ] ]  }

    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:GetObject"
      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "TranscodedBucket" }, '/*' ] ]  }
    
# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
#   transcode:
#     handler: aws/lambda-transcode.handler
#     timeout: 300 # use all the AWS Maximum execution duration per request limit
#     events:
#       - http:
#           path: transcode
#           method: GET

  app-express:
    handler: aws/lambda-express.handler
    timeout: 30
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

resources:
  Resources:
    TranscodedBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.s3Bucket}
